# CircleCI 2.0 configuration file for dronekit-python

# Steps common to both Python 2 and Python 3
common: &commonsteps
    steps:
        - checkout

        - run:
              name: Install dronekit with dependencies
              command: |
                  virtualenv venv
                  source venv/bin/activate
                  pip install -UI future
                  pip install -r requirements.txt -UI
                  pip install . -UI

        - run:
              name: Run dronekit tests
              environment:
                  SITL_SPEEDUP: 10
                  SITL_RATE: 200
              command: |
                  source venv/bin/activate
                  nosetests -svx dronekit.test.unit
                  nosetests -svx dronekit.test.sitl

# Jobs definition
version: 2
jobs:
    python2:
        docker:
            - image: circleci/python:2.7-stretch
        working_directory: ~/dronekit-python2
        <<: *commonsteps

    python3:
        docker:
            - image: circleci/python:3.6-stretch
        working_directory: ~/dronekit-python3
        <<: *commonsteps

    px4:
        docker:
            - image: circleci/python:3.6-stretch
        working_directory: ~/dronekit-python3
        steps:
            - setup_remote_docker:
                  docker_layer_caching: true
            - checkout
            - run:
                  name: "Launch PX4 into Docker"
                  command: |
                      docker run -it \
                      -p 14556:14556/udp \
                      --name=px4container px4io/px4-dev-simulation:latest \
                      bash -c "git clone -b stable https://github.com/PX4/Firmware.git ~/firmware && cd ~/firmware && make posix_sitl_default gazebo"
            - run:
                  name: "Sleep"
                  command: "sleep 10"



# Workflow definition
# Run Python 2 and Python 3 testing in parallel
# and deploy if the Python 2 build succeeds
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - px4
